services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3002:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./netlify
      dockerfile: Dockerfile.backend
    image: arm64v8/node:18
    platform: linux/arm64/v8
    ports:
      - "3001:3001"
    volumes:
      - ./netlify/data:/app/data
      - ./netlify/dist:/app/dist
    environment:
      - PORT=3001
      - BETTER_SQLITE3_BINARY_HOST_MIRROR=https://github.com/WiseLibs/better-sqlite3/releases/download
